"""Registry metadata for every metric and inference method exposed by the UI."""

from __future__ import annotations

from copy import deepcopy
from typing import Any


def _method(
    identifier: str,
    name: str,
    family: str,
    question: str,
    definition: str,
    *,
    inputs: list[str],
    calculation: str,
    interpretation: str,
    limitations: str,
    formula: str = "Not applicable",
    raw_latex: str = "",
    output: str = "0–1 normalised diagnostic unless stated otherwise",
    normalisation: str = "Fixed reference range or explicitly labelled structural transform",
    objects: list[str] | None = None,
    layers: list[str] | None = None,
    cost: str = "low",
    reference: str = "PRIMROSE method catalogue",
    contributes_to: list[str] | None = None,
    enabled: bool = True,
    unavailable_when: str = "Required inputs are absent.",
    assumptions: str = "The configured typed graph projection matches the analytical question.",
) -> dict[str, Any]:
    return {
        "id": identifier,
        "display_name": name,
        "family": family,
        "supported_object_types": objects or ["node"],
        "definition": definition,
        "analytical_question": question,
        "required_inputs": inputs,
        "calculation": calculation,
        "formula": formula,
        "raw_latex": raw_latex,
        "output_range_units": output,
        "normalisation": normalisation,
        "interpretation": interpretation,
        "assumptions": assumptions,
        "limitations": limitations,
        "failure_modes": limitations,
        "computational_cost": cost,
        "required_graph_layers": layers or ["configured typed projection"],
        "reference": reference,
        "version": "1.0.0",
        "contributes_to_score": bool(contributes_to),
        "score_profiles": contributes_to or [],
        "default_enabled": enabled,
        "unavailable_when": unavailable_when,
    }


METHODS: list[dict[str, Any]] = [
    _method(
        "mission.consequence", "Mission consequence", "Mission",
        "How consequential is loss or degradation in this decision context?",
        "A context-bound consequence assessment sourced from explicit graph metadata or an analyst entry.",
        inputs=["versioned decision context", "criticality or analyst consequence assessment"],
        calculation="Maps configured categorical or numeric consequence values to a fixed reference scale; records the source of the value.",
        formula="Configured consequence mapping", raw_latex=r"M \in [0,1]",
        interpretation="Higher means greater consequence in this context, not greater certainty.",
        limitations="Unavailable when the graph and analyst context contain no consequence assessment.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "functional.dependency", "Functional dependency", "Mission",
        "How much mission-relevant function depends on this object?",
        "A typed dependency diagnostic using configured dependency relations and bounded downstream reach.",
        inputs=["directed typed relationships", "relation-role mapping"],
        calculation="Combines weighted direct dependency edges and two-hop typed reach against fixed caps.",
        formula="One minus exponential decay of weighted dependency load",
        raw_latex=r"D = 1-e^{-(w_d k_d + w_r r_2)/c}",
        interpretation="Higher indicates more recorded functional dependence.",
        limitations="Direction or predicate misuse can invert the result; it is not a causal effect estimate.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "resilience.non_substitutability", "Non-substitutability", "Resilience",
        "Are equivalent alternatives recorded for the same function?",
        "A structural proxy based on comparable typed objects serving overlapping neighbours.",
        inputs=["object type or function", "typed neighbourhood"],
        calculation="Counts comparable alternatives with shared functional neighbours and converts the count with a fixed inverse transform.",
        formula="Inverse alternative count", raw_latex=r"N = \frac{1}{1+s}",
        interpretation="Higher means fewer recorded substitutes.",
        limitations="Missing alternatives in the collection can look like genuine uniqueness; label as a structural proxy.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "temporal.urgency", "Temporal urgency", "Temporal",
        "How quickly could the assessment become stale or the decision window close?",
        "A time-window diagnostic based on explicit valid, observation and review times.",
        inputs=["valid time", "observation time", "decision horizon"],
        calculation="Uses the nearest explicit expiry or decision deadline against fixed day bands.",
        formula="Time-to-deadline band", raw_latex=r"U = \max(0,1-\Delta t/T)",
        interpretation="Higher indicates a shorter explicit decision or validity window.",
        limitations="Ingestion time is not operational time; unavailable when appropriate timestamps are absent.",
        contributes_to=["operational-criticality-v1", "collection-priority-v1", "hypothesis-review-v1", "contradiction-review-v1"],
    ),
    _method(
        "multilayer.cross_layer_dependency", "Cross-layer dependency", "Multilayer",
        "Across how many configured operational layers does this object connect?",
        "Participation across configurable physical, command, communications, logistics, financial, cyber, influence, organisational, production and transport layers.",
        inputs=["relation-to-layer mapping", "typed incident relationships"],
        calculation="Counts distinct configured layers and applies a fixed ten-layer reference.",
        formula="Observed layers divided by configured reference", raw_latex=r"X = |L_v|/|L_{ref}|",
        interpretation="Higher indicates broader cross-layer involvement, not necessarily importance.",
        limitations="Results depend on documented layer definitions; predicates are not automatically valid layers.",
        layers=["all configured layers"], contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "centrality.typed_weighted_degree", "Typed weighted degree", "Classical graph",
        "How much configured relationship weight is incident on this object?",
        "In- and out-degree calculated on typed relations using explicit relation weights.",
        inputs=["directed typed graph", "relation weights"],
        calculation="Sums configured weights on incident edges; preserves direction in the trace.",
        formula="Weighted incident degree", raw_latex=r"k_w(v)=\sum_{e\ni v} w_{type(e)}",
        interpretation="Higher means more weighted recorded connections in this projection.",
        limitations="Collection bias and duplicated assertions can create false hubs; degree is not mission consequence.",
    ),
    _method(
        "centrality.local_reach", "Typed local reach", "Classical graph",
        "How many objects are reachable within the configured local horizon?",
        "Bounded directed reach using only permitted relationship types.",
        inputs=["typed projection", "depth", "direction"],
        calculation="Breadth-first traversal to depth two, normalised against a fixed reference cap.",
        formula="Bounded reachable set", raw_latex=r"R_h(v)=|\{u:d(v,u)\le h\}|",
        interpretation="Higher indicates a broader recorded local neighbourhood.",
        limitations="Does not imply influence or physical flow unless the projection semantics support that reading.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "centrality.pagerank", "PageRank", "Classical graph",
        "Which objects receive links from other structurally prominent objects?",
        "A direction-sensitive random-walk diagnostic on the selected typed projection.",
        inputs=["directed projection", "damping factor"],
        calculation="Power iteration with explicit dangling-node redistribution.",
        formula="PageRank recurrence", raw_latex=r"PR(v)=\frac{1-d}{N}+d\sum_{u\to v}\frac{PR(u)}{L(u)}",
        interpretation="Higher is structurally prominent only when edge direction has a defensible meaning.",
        limitations="Ranks collection patterns when direction or relation semantics are incoherent; display diagnostic only by default.",
    ),
    _method(
        "centrality.personalized_pagerank", "Mission-seeded PageRank", "Classical graph",
        "Which objects are structurally close to explicit mission seeds?",
        "PageRank whose restart distribution is restricted to versioned decision-context seeds.",
        inputs=["directed typed projection", "mission seed ids"],
        calculation="Power iteration with restart mass distributed across valid mission seeds.",
        formula="Personalised PageRank", raw_latex=r"\pi=(1-d)s+dP^T\pi",
        interpretation="Higher means more walk-based proximity to the stated seeds.",
        limitations="Seed choice and graph incompleteness materially affect rank; never treat as permanent node importance.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "centrality.harmonic_proximity", "Harmonic proximity", "Classical graph",
        "How close is this object to the rest of the selected graph, including disconnected cases?",
        "The average reciprocal shortest-path distance on the configured projection.",
        inputs=["typed projection", "direction policy"],
        calculation="Breadth-first distances with unreachable nodes contributing zero.",
        formula="Harmonic centrality", raw_latex=r"H(v)=\frac{1}{N-1}\sum_{u\ne v}\frac{1}{d(v,u)}",
        interpretation="Higher indicates shorter recorded paths to more objects.",
        limitations="Path length has no operational meaning without defensible relation semantics.",
        cost="medium",
    ),
    _method(
        "structure.participation_coefficient", "Participation coefficient", "Communities and bridges",
        "Is the object connected across several configured layers or communities?",
        "Dispersion of an object's incident links across configured groups.",
        inputs=["community or layer assignments", "incident edges"],
        calculation="One minus the sum of squared within-group degree shares.",
        formula="Participation coefficient", raw_latex=r"P_i=1-\sum_s(k_{is}/k_i)^2",
        interpretation="Higher indicates more evenly distributed cross-group connectivity.",
        limitations="A degree-one cross-group node is not automatically a strategic bridge; combine with cut and alternate-path tests.",
    ),
    _method(
        "structure.articulation", "Articulation point", "Communities and bridges",
        "Would removing this object split the structural projection?",
        "A binary cut-vertex diagnostic on an explicitly undirected structural projection.",
        inputs=["undirected structural projection"],
        calculation="Tarjan depth-first low-link search.",
        formula="Binary graph property", raw_latex=r"A(v)=\mathbb{1}[c(G-v)>c(G)]",
        output="Boolean plus affected-component context",
        interpretation="True identifies a structural single connector in this projection.",
        limitations="Does not establish real-world failure propagation, capacity loss or causation.",
    ),
    _method(
        "structure.bridge_participation", "Bridge and participation", "Communities and bridges",
        "Is this object both cross-group and structurally difficult to bypass?",
        "Composite structural diagnostic combining participation, articulation exposure and alternate-path loss.",
        inputs=["participation coefficient", "articulation status", "alternate-path loss"],
        calculation="Fixed weighted structural composite; every contribution is retained in the trace.",
        formula="Structural bridge composite", raw_latex=r"B=0.35P+0.30A+0.35L_{alt}",
        interpretation="Higher indicates stronger structural bridge evidence.",
        limitations="Remains a structural proxy and inherits projection and missing-edge sensitivity.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "resilience.alternate_path_loss", "Alternate-path loss", "Resilience",
        "How many direct relationships lack another recorded route between their endpoints?",
        "The share of incident connections for which no alternate structural path exists after removing the direct edge.",
        inputs=["structural projection", "incident edges"],
        calculation="Edge-by-edge reachability test with the direct edge excluded.",
        formula="Non-redundant incident-edge share", raw_latex=r"L_{alt}=1-|E_{bypass}|/|E_v|",
        interpretation="Higher indicates less recorded route redundancy.",
        limitations="Ignores capacity, delay and substitutability unless those are separately modelled.",
        cost="medium", contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "resilience.robustness_loss", "Structural robustness loss", "Resilience",
        "How much seed reachability is lost when the object is removed?",
        "A mission-seed reachability stress test on the selected structural projection.",
        inputs=["mission seeds", "structural projection"],
        calculation="Compares reachable nodes before and after removing the object.",
        formula="Fractional reach loss", raw_latex=r"L_v=(R(G)-R(G-v))/\max(1,R(G))",
        interpretation="Higher means greater structural reach loss in this graph snapshot.",
        limitations="A structural deletion test is not a causal cascade, capacity model or forecast.",
        cost="medium",
    ),
    _method(
        "resilience.redundancy", "Redundancy", "Resilience",
        "How much recorded path or substitute coverage remains?",
        "A labelled structural proxy based on alternate routes and comparable substitutes.",
        inputs=["alternate paths", "substitute candidates"],
        calculation="Combines bypass share and explicit substitute coverage when available.",
        formula="Fixed proxy composite", raw_latex=r"R=0.6R_{path}+0.4R_{sub}",
        interpretation="Higher indicates more recorded alternatives.",
        limitations="Cannot represent real capacity, recovery time or reliability without additional data.",
    ),
    _method(
        "evidence.provenance_completeness", "Provenance completeness", "Evidence",
        "Are the required source and derivation fields present?",
        "Completeness of source identifier, passage, lineage, model version and time metadata.",
        inputs=["assertion provenance"],
        calculation="Fixed required-field checklist; missing fields remain visible in the trace.",
        formula="Present required fields divided by required fields", raw_latex=r"C_p=|F_{present}|/|F_{required}|",
        interpretation="Higher means more auditable provenance, not that the assertion is true.",
        limitations="Complete metadata can still describe unreliable or false reporting.",
        contributes_to=["evidential-confidence-v1"],
    ),
    _method(
        "evidence.independent_corroboration", "Independent corroboration", "Evidence",
        "How many genuinely independent source lineages support the assertion?",
        "Support count adjusted so derivative reports from one origin do not multiply confidence.",
        inputs=["source lineage", "support polarity"],
        calculation="Counts distinct originating lineages with diminishing returns.",
        formula="Lineage-adjusted support", raw_latex=r"C_i=1-e^{-n_{ind}/2}",
        interpretation="Higher means support from more independent origins.",
        limitations="Unavailable when reporting lineage is not recorded; document count alone is not independence.",
        contributes_to=["evidential-confidence-v1"],
    ),
    _method(
        "evidence.extraction_resolution_certainty", "Extraction and resolution certainty", "Evidence",
        "How certain are the extraction span and entity resolution?",
        "Combined recorded certainty for grounded extraction and reviewed identity resolution.",
        inputs=["extraction certainty", "entity-resolution certainty"],
        calculation="Uses the lower of the two recorded values so one cannot compensate for the other.",
        formula="Non-compensatory minimum", raw_latex=r"C_{er}=\min(C_e,C_r)",
        interpretation="Higher means both extraction and identity linkage are better supported.",
        limitations="Raw model scores are not probabilities unless calibrated.",
        contributes_to=["evidential-confidence-v1"],
    ),
    _method(
        "evidence.source_reliability", "Source reliability", "Evidence",
        "How consistently reliable is the recorded source?",
        "Explicit source-level reliability assessment kept separate from information credibility.",
        inputs=["source reliability assessment"],
        calculation="Maps configured reliability grades to a fixed scale while preserving the original grade.",
        formula="Configured grade mapping", raw_latex=r"R_s \in [0,1]",
        interpretation="Higher indicates a more reliable source assessment.",
        limitations="Must not be inferred from source type or prestige when no assessment exists.",
        contributes_to=["evidential-confidence-v1"],
    ),
    _method(
        "evidence.information_credibility", "Information credibility", "Evidence",
        "How credible and direct is the reported information itself?",
        "Explicit information-level credibility and directness assessment.",
        inputs=["credibility", "directness"],
        calculation="Non-compensatory combination of recorded credibility and directness.",
        formula="Geometric mean when both inputs exist", raw_latex=r"C_m=\sqrt{C_i C_d}",
        interpretation="Higher indicates more credible, direct information.",
        limitations="Unavailable rather than guessed when credibility or directness is absent.",
        contributes_to=["evidential-confidence-v1"],
    ),
    _method(
        "evidence.temporal_validity", "Temporal validity", "Evidence",
        "Is the evidence valid for the decision's time horizon?",
        "Compatibility between explicit assertion validity and the decision context.",
        inputs=["valid time", "observation time", "decision horizon"],
        calculation="Checks interval overlap and applies an explicit recency decay only where configured.",
        formula="Interval overlap with optional decay", raw_latex=r"V_t=\mathbb{1}[I_a\cap I_d\ne\varnothing]e^{-\lambda\Delta t}",
        interpretation="Higher indicates better temporal fit.",
        limitations="Report or ingestion time cannot substitute for event or valid time.",
        contributes_to=["evidential-confidence-v1"],
    ),
    _method(
        "contradiction.severity", "Contradiction severity", "Contradiction",
        "How material is a conflict between assertions?",
        "Conflict diagnostic combining polarity, scope overlap, lineage independence and mission consequence.",
        inputs=["conflicting assertions", "polarity", "time scope", "lineage"],
        calculation="Only compares assertions whose subject, predicate, object and valid-time scopes are compatible.",
        formula="Configured severity factors", raw_latex=r"S_c=P\times T\times I\times M",
        interpretation="Higher means a more consequential unresolved conflict.",
        limitations="Absence of a contradiction record is not proof of agreement.",
        contributes_to=["contradiction-review-v1"],
    ),
    _method(
        "collection.decision_sensitivity", "Decision sensitivity", "Collection",
        "Would resolving this uncertainty plausibly change the decision?",
        "A traceable proxy based on consequence, score coverage and rank instability.",
        inputs=["decision context", "unresolved inputs", "sensitivity runs"],
        calculation="Combines unresolved high-weight contributions and observed rank range without treating missingness as a generic bonus.",
        formula="Unresolved weighted consequence", raw_latex=r"S_d=\sum_{j\in missing} w_j M_j",
        interpretation="Higher means the missing input is more decision-relevant.",
        limitations="A full expected-value model requires decision alternatives and utilities.",
        contributes_to=["collection-priority-v1"],
    ),
    _method(
        "structural.component", "Structural diagnostic component", "Composite",
        "What does the configured structural evidence contribute after stability checks?",
        "A non-renormalised subscore over mission-seeded PageRank, bridge participation, alternate-path loss, local reach and community-role stability.",
        inputs=["all configured structural submetrics", "versioned structural weights"],
        calculation="Applies the profile's structural_weights only when every required submetric is available; otherwise the component remains unavailable.",
        formula="Weighted structural subscore", raw_latex=r"S=0.30PPR+0.25B+0.25L_{alt}+0.10R_2+0.10S_r",
        interpretation="Higher describes stronger and more stable structural diagnostics in the selected projection.",
        limitations="It is not mission consequence or a causal effect; missing seeds or perturbation runs make the component unavailable.",
        contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "collection.assessment_change_likelihood", "Assessment-change likelihood", "Collection",
        "How likely is resolving this gap to change the current assessment?",
        "A calibrated estimate conditioned on prior comparable collection outcomes and the specific unresolved assessment input.",
        inputs=["adjudicated historical collection outcomes", "current uncertainty", "assessment-change labels"],
        calculation="Uses a validated, versioned outcome model; no value is emitted without an adequate out-of-sample calibration set.",
        formula="Conditional outcome probability", raw_latex=r"P(\Delta A\mid q,x)",
        interpretation="Higher means comparable questions more often changed the relevant assessment.",
        limitations="Not inferable from graph missingness alone; transport across missions and source families can fail.",
        enabled=False, contributes_to=["collection-priority-v1"],
    ),
    _method(
        "collection.unresolved_consequence", "Unresolved consequence", "Collection",
        "How consequential would the unresolved issue be if the adverse case were true?",
        "A consequence-bounded description of an identified evidence gap, kept separate from the likelihood that the adverse case is true.",
        inputs=["explicit unresolved question", "decision context", "consequence assessment"],
        calculation="Maps an analyst-recorded adverse-case consequence through the context's fixed consequence scale.",
        formula="Configured adverse-case consequence", raw_latex=r"C_u=C(\theta_{adverse},d)",
        interpretation="Higher means the unresolved branch is more consequential, not more probable.",
        limitations="Requires a specific question and context; generic uncertainty must not receive a consequence bonus.",
        contributes_to=["collection-priority-v1"],
    ),
    _method(
        "collection.feasibility", "Collection feasibility", "Collection",
        "Can the identified information requirement realistically be answered in time?",
        "An explicit assessment of access, timeliness, cost, legal or policy constraints and expected observability.",
        inputs=["specific collection question", "available collection options", "deadline", "constraints"],
        calculation="Applies a configured rubric whose dimensions and assessor remain in the trace.",
        formula="Configured feasibility rubric", raw_latex=r"F_c=f(a,t,c,l,o)",
        interpretation="Higher indicates a more feasible collection option under the recorded constraints.",
        limitations="Cannot be inferred from graph structure and must not reveal sensitive collection capabilities to unauthorised users.",
        contributes_to=["collection-priority-v1", "hypothesis-review-v1"],
    ),
    _method(
        "hypothesis.mission_consequence_if_true", "Hypothesis consequence if true", "Hypothesis",
        "If this candidate relationship were true, how much could it matter to the stated decision?",
        "A counterfactual consequence assessment that deliberately does not estimate candidate truth.",
        inputs=["candidate triple", "versioned decision context", "explicit consequence mapping"],
        calculation="Evaluates the recorded consequence branch under the assumption that the candidate is true.",
        formula="Conditional consequence", raw_latex=r"M_h=C(d\mid h=1)",
        interpretation="Higher means greater consequence conditional on truth, not greater plausibility.",
        limitations="Requires a real decision context; structural novelty cannot substitute for consequence.",
        objects=["relationship hypothesis"], contributes_to=["hypothesis-review-v1"],
    ),
    _method(
        "hypothesis.calibrated_plausibility", "Calibrated hypothesis plausibility", "Hypothesis assurance",
        "How well does a relation-specific calibrated model support this candidate?",
        "A relation- and context-conditioned calibrated output derived from adjudicated, leakage-controlled evaluation data.",
        inputs=["raw candidate score", "relation-specific calibrator", "adjudicated holdout outcomes"],
        calculation="Applies only a passing, versioned calibrator and reports reliability and abstention metadata beside the value.",
        formula="Calibrated mapping", raw_latex=r"p_h=g_r(s_h)",
        interpretation="Higher is a calibrated model estimate within its validated domain; it is still not evidence.",
        limitations="Unavailable for raw ULTRA scores without relation-specific calibration or under distribution shift.",
        objects=["relationship hypothesis"], enabled=False, contributes_to=["hypothesis-review-v1"],
    ),
    _method(
        "hypothesis.independent_agreement", "Independent hypothesis agreement", "Hypothesis assurance",
        "Do genuinely independent hypothesis methods rank the same candidate?",
        "Agreement across methods with distinct training signals, after shared inputs and rules are identified.",
        inputs=["candidate outputs from independent methods", "method lineage", "comparison set"],
        calculation="Counts lineage-distinct agreeing methods with a fixed cap and records disagreements and shared dependencies.",
        formula="Lineage-distinct agreement", raw_latex=r"A_h=|G_{ind}(h)|/G_{ref}",
        interpretation="Higher indicates broader method agreement, not independent source corroboration.",
        limitations="Two models trained on the same graph are not automatically independent; agreement can reproduce shared bias.",
        objects=["relationship hypothesis"], enabled=False, contributes_to=["hypothesis-review-v1"],
    ),
    _method(
        "contradiction.unresolved_consequence", "Contradiction unresolved consequence", "Contradiction",
        "What is the consequence of leaving this material contradiction unresolved?",
        "A context-specific consequence assessment attached to the exact incompatible assertion set.",
        inputs=["compatible contradiction set", "decision context", "affected assessment"],
        calculation="Maps the analyst-recorded unresolved consequence through a fixed context scale.",
        formula="Context consequence", raw_latex=r"C_{cu}=C(d\mid c\ unresolved)",
        interpretation="Higher means the unresolved conflict has greater decision consequence.",
        limitations="Requires a real contradiction object and decision context; conflict count is not consequence.",
        objects=["contradiction"], contributes_to=["contradiction-review-v1"],
    ),
    _method(
        "contradiction.lineage_independence", "Contradiction lineage independence", "Contradiction",
        "Do the conflicting claims originate from genuinely distinct source lineages?",
        "A derivation-aware check that distinguishes independent conflict from repeated reporting of one origin.",
        inputs=["assertion provenance", "source-dependency graph", "conflict set"],
        calculation="Counts distinct originating lineages and flags unknown or circular derivations.",
        formula="Independent-origin share", raw_latex=r"I_c=|L_{ind}|/|L_{claims}|",
        interpretation="Higher means the conflict spans more independent origins and may be more substantive.",
        limitations="Unavailable when lineage is missing; document or outlet count alone is not independence.",
        objects=["contradiction"], contributes_to=["contradiction-review-v1"],
    ),
    _method(
        "contradiction.resolution_likelihood", "Contradiction resolution likelihood", "Contradiction",
        "How likely is the proposed review or collection step to resolve this conflict?",
        "An outcome-calibrated estimate for a specific resolution action and contradiction class.",
        inputs=["specific resolution action", "contradiction class", "historical adjudicated outcomes"],
        calculation="Uses a validated outcome model or an explicit analyst rubric; otherwise remains unavailable.",
        formula="Conditional resolution probability", raw_latex=r"P(R=1\mid a,c)",
        interpretation="Higher indicates a better prospect of resolving this exact conflict with the proposed action.",
        limitations="Cannot be inferred from graph proximity; historical performance may not transfer to new sources or contexts.",
        objects=["contradiction"], enabled=False, contributes_to=["contradiction-review-v1"],
    ),
    _method(
        "collection.expected_information_gain", "Expected information gain", "Collection",
        "How much could a proposed collection question reduce uncertainty?",
        "An adapter for entropy or decision-model reduction when prior and observation models exist.",
        inputs=["prior distribution", "observation model", "collection option"],
        calculation="Unavailable unless the required probabilistic decision model is configured.",
        formula="Expected entropy reduction", raw_latex=r"EIG=H(\Theta)-\mathbb{E}_Y[H(\Theta|Y)]",
        interpretation="Higher predicts greater uncertainty reduction under the stated model.",
        limitations="The current repository has no calibrated prior or observation model; no value is fabricated.",
        enabled=False, contributes_to=["hypothesis-review-v1"],
    ),
    _method(
        "temporal.activity_change", "Collection-normalised activity change", "Temporal",
        "Did activity change beyond what reporting volume alone explains?",
        "Change in valid-time activity normalised by collection volume and source lineage.",
        inputs=["event or valid times", "collection volume", "source lineages", "comparison window"],
        calculation="Compares rate ratios across fixed windows with collection-volume adjustment.",
        formula="Normalised rate ratio", raw_latex=r"\Delta_a=(E_1/C_1)-(E_0/C_0)",
        interpretation="Positive values indicate increased activity after collection adjustment.",
        limitations="Unavailable on a single snapshot or when only ingestion timestamps exist.",
        enabled=False,
    ),
    _method(
        "temporal.change_point", "Change-point detection", "Temporal",
        "When did the activity-generating process materially change?",
        "Adapter for a configured statistical change-point detector over event-time series.",
        inputs=["sufficient event-time series", "minimum history", "detector configuration"],
        calculation="Production adapter; current static graph has insufficient chronological observations.",
        formula="Detector-specific posterior or test statistic", raw_latex=r"P(\tau=t\mid x_{1:T})",
        interpretation="A detected point identifies a statistical regime change, not a causal explanation.",
        limitations="Reporting bursts and bulk imports can create false changes; requires collection normalisation.",
        enabled=False,
    ),
    _method(
        "community.leiden", "Leiden communities", "Communities and bridges",
        "Which densely connected groups appear in a coherent projection?",
        "Modularity-based community detection using a production adapter for Leiden.",
        inputs=["weighted projection", "resolution", "random seed"],
        calculation="Adapter is unavailable until an audited Leiden implementation is installed.",
        formula="Modularity quality objective", raw_latex=r"Q=\frac{1}{2m}\sum_{ij}(A_{ij}-\gamma P_{ij})\delta(c_i,c_j)",
        interpretation="Communities are descriptive partitions, not real organisational boundaries.",
        limitations="Resolution and seed affect results; current standard-library runtime does not ship Leiden.",
        enabled=False,
    ),
    _method(
        "community.role_stability", "Community-role stability", "Communities and bridges",
        "Does the object's role persist across seeds and plausible graph perturbations?",
        "Rank and community-role stability under documented perturbation runs.",
        inputs=["community runs", "graph perturbations", "seed set"],
        calculation="Reports the share of runs retaining the same role and a rank interval.",
        formula="Stable-run share", raw_latex=r"S_r=|\{b:r_b=r_0\}|/B",
        interpretation="Higher indicates a more stable structural role.",
        limitations="Unavailable until perturbation runs have completed.",
        enabled=False, contributes_to=["operational-criticality-v1"],
    ),
    _method(
        "hypothesis.ultra", "ULTRA link candidate", "Hypothesis",
        "Which binary triples does the configured ULTRA model rank for review?",
        "A static structure-only link-ranking adapter kept in the hypothesis layer.",
        inputs=["accepted training graph", "ULTRA model", "candidate relation"],
        calculation="Production adapter; preserves raw relation-specific rank and never calls the score a probability.",
        formula="Model-specific uncalibrated score", raw_latex=r"s_{ULTRA}(h,r,t)",
        output="Raw uncalibrated score, rank and optional calibrated set",
        interpretation="Higher raw score means higher model rank only within its valid comparison set.",
        limitations="Not causal inference, temporal forecasting or evidence; raw scores are not comparable across relations.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.anyburl", "AnyBURL / AMIE symbolic rules", "Hypothesis",
        "Which candidate links are supported by interpretable graph rules?",
        "Adapter for an independent symbolic-rule hypothesis generator and challenger.",
        inputs=["accepted typed graph", "rule-miner runtime"],
        calculation="Returns rule text, support, confidence, body coverage, paths and exceptions.",
        formula="Rule confidence", raw_latex=r"conf(B\Rightarrow H)=support(B\land H)/support(B)",
        interpretation="Higher rule confidence describes historical rule fit, not truth of a candidate.",
        limitations="Unavailable until a licensed, containerised rule runtime is configured; leakage and tautological rules require review.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.tlogic", "TLogic / TILP temporal rules", "Hypothesis",
        "Which relationship may occur within an explicit future horizon?",
        "Adapter for explainable temporal rules over event sequences.",
        inputs=["event-centric temporal graph", "temporal-rule runtime", "forecast horizon"],
        calculation="Returns temporal rule, supporting sequence, ordering, recurrence, confidence and exceptions.",
        formula="Temporal rule confidence", raw_latex=r"conf(R_{time})=support(R_{body}\land R_{head})/support(R_{body})",
        interpretation="A ranked temporal hypothesis requires independent evidence and analyst review.",
        limitations="The current binary static graph lacks sufficient event-time training data.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.calibration", "Relation-specific calibration", "Hypothesis assurance",
        "How well do model scores correspond to adjudicated outcomes for this relation?",
        "Calibration and conformal-prediction adapter conditioned on relation and evaluation split.",
        inputs=["adjudicated outcomes", "chronological source-family-disjoint split", "raw scores"],
        calculation="Reliability, Brier-style scoring, coverage, abstention and conformal answer sets when data suffice.",
        formula="Brier score", raw_latex=r"BS=\frac{1}{N}\sum_i(p_i-y_i)^2",
        interpretation="A calibrated output may support uncertainty communication; it still is not evidence.",
        limitations="Unavailable without sufficient independent adjudicated outcomes; raw ULTRA scores remain uncalibrated.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "retrieval.graphrag", "GraphRAG retrieval and synthesis", "Retrieval",
        "What evidence and graph context answer a broad or multi-hop question?",
        "Bounded retrieval over the canonical review-filtered graph followed by evidence-grounded synthesis.",
        inputs=["canonical graph", "evidence store", "question", "access scope"],
        calculation="Routes and retrieves context; it has no numerical score weight.",
        formula="No scoring formula", raw_latex="",
        output="Answer, consulted records, citations and deterministic trace",
        interpretation="Useful for context and explanation; direct graph queries remain authoritative for exact facts.",
        limitations="Synthesis can omit or misstate context; citations and deterministic traces must be inspected.",
        objects=["question"], contributes_to=[],
    ),
    _method(
        "model.gemma4", "Gemma-4 explanation provider", "Model synthesis",
        "How can deterministic traces and retrieved evidence be translated into analyst-readable text?",
        "A provider-labelled adapter for structured, cited synthesis; it cannot change metrics or graph state.",
        inputs=["configured model id", "OpenAI-compatible endpoint", "bounded evidence", "JSON schema"],
        calculation="Calls the configured provider only when explicitly enabled; otherwise returns a deterministic explanation.",
        formula="No scoring formula", raw_latex="",
        output="Schema-validated explanation with evidence ids and unresolved inferences",
        interpretation="Generated prose is synthesis, not source evidence or a deterministic calculation.",
        limitations="Disabled until the actual Gemma-4 model id and endpoint are configured; retrieved text is treated as untrusted data.",
        objects=["explanation"], enabled=False,
    ),
]

# Additional catalogue entries cover the complete analytical families in the
# design brief.  Implemented static-graph diagnostics remain display-only
# unless a versioned profile explicitly names them.  Methods requiring data,
# history or a runtime that this repository does not have are registered but
# disabled, so clients can explain the honest unavailable state.
METHODS.extend([
    _method(
        "functional.role", "Typed functional role", "Mission",
        "Which directed relation roles are recorded for this object?",
        "A histogram of incoming and outgoing typed relationship roles in the selected projection.",
        inputs=["directed typed projection"],
        calculation="Counts each distinct direction–predicate role after duplicate assertion fusion.",
        formula="Directed role count", raw_latex=r"F(v)=\{(d,r,k_{d,r})\}",
        output="Role-count mapping plus bounded display diagnostic",
        interpretation="More roles indicate broader recorded functional participation, not greater consequence.",
        limitations="Predicate direction and ontology quality determine whether a role interpretation is defensible.",
    ),
    _method(
        "mission.strategic_consequence", "Analyst-assessed strategic consequence", "Mission",
        "What strategic consequence does the analyst assess in this versioned context?",
        "An explicitly analyst-entered consequence assessment kept separate from calculated structure and evidence confidence.",
        inputs=["analyst identity", "decision context", "assessment", "rationale"],
        calculation="Maps only an authenticated analyst assessment through the context's configured scale.",
        formula="Configured analyst assessment", raw_latex=r"C_s=a(v,d)",
        interpretation="Higher means the analyst assessed greater strategic consequence in this context.",
        limitations="Unavailable without an attributable assessment; the system must never infer it from centrality.",
        enabled=False,
    ),
    _method(
        "centrality.betweenness_structural", "Structural betweenness", "Classical graph",
        "How often does the object lie on shortest structural paths?",
        "Normalised unweighted Brandes betweenness on the simple undirected projection restricted to configured dependency predicates.",
        inputs=["coherent configured dependency-predicate projection"],
        calculation="Counts fractions of shortest paths traversing the node and applies the undirected normalisation.",
        formula="Normalised betweenness", raw_latex=r"B(v)=\frac{2}{(n-1)(n-2)}\sum_{s<t}\frac{\sigma_{st}(v)}{\sigma_{st}}",
        interpretation="Higher means more shortest structural paths pass through the node in this projection.",
        limitations="Display diagnostic only unless these dependency predicates and shortest paths form a defensible flow model; it is not traffic, influence or causal control.",
        cost="medium",
    ),
    _method(
        "centrality.core_membership", "k-core membership", "Classical graph",
        "In which reversible structural core does this object appear?",
        "Undirected core number calculated without deleting or permanently excluding any object.",
        inputs=["simple structural projection"],
        calculation="Deterministic degeneracy peeling records each node's core number; the source graph is unchanged.",
        formula="Core number", raw_latex=r"c(v)=\max\{k:v\in C_k\}",
        output="Non-negative integer plus graph-relative display scale",
        interpretation="Higher means membership in a denser structural subgraph.",
        limitations="Display and reversible simplification only; low core number is not low operational importance.",
    ),
    _method(
        "centrality.within_community_role", "Within-community role", "Communities and bridges",
        "How connected is the object within a frozen community assignment?",
        "Within-community degree or z-score conditioned on a versioned community partition.",
        inputs=["frozen community assignment", "typed weighted projection"],
        calculation="Computes within-community degree and a documented standardisation only when the group has sufficient members.",
        formula="Within-module degree z-score", raw_latex=r"z_i=(k_{i,s}-\mu_{k_s})/\sigma_{k_s}",
        interpretation="Higher indicates a stronger recorded within-community role.",
        limitations="Unavailable without a frozen partition; small groups and resolution choices make z-scores unstable.",
        enabled=False,
    ),
    _method(
        "centrality.ranking_stability", "Centrality and ranking stability", "Classical graph",
        "Does this object's rank persist under documented perturbations?",
        "Rank interval and retention across graph bootstraps, source-family removals and configuration variants.",
        inputs=["frozen baseline rank", "documented perturbation runs"],
        calculation="Summarises rank intervals and top-k retention without hiding perturbation design.",
        formula="Top-k retention", raw_latex=r"S_k=|R_k\cap R_k^{(b)}|/k",
        interpretation="Higher indicates a more stable structural ranking under tested perturbations.",
        limitations="Unavailable on one run; stability to tested perturbations does not prove external validity.",
        enabled=False, cost="high",
    ),
    _method(
        "structure.bridge_edge_exposure", "Bridge-edge exposure", "Communities and bridges",
        "What share of this object's incident endpoint pairs are structural bridges?",
        "Incident exposure to endpoint pairs whose removal increases component count in the undirected projection.",
        inputs=["simple undirected structural projection"],
        calculation="Tarjan low-link bridge search followed by the incident bridge-pair share.",
        formula="Incident bridge share", raw_latex=r"E_b(v)=|B\cap E_v|/|E_v|",
        interpretation="Higher means more incident structural connections have no endpoint-pair bypass.",
        limitations="Does not imply a physical single link, capacity loss or causal failure; parallel assertions are fused.",
    ),
    _method(
        "structure.cut_set_exposure", "Single-node cut exposure", "Communities and bridges",
        "How much pairwise connectivity is structurally separated by removing this node?",
        "Fraction of connected remaining-node pairs in the node's component that become separated after node removal.",
        inputs=["simple undirected structural projection"],
        calculation="Compares pair connectivity in the original component with residual component sizes after one-node deletion.",
        formula="Separated pair share", raw_latex=r"C_v=1-\frac{\sum_j {|S_j|\choose2}}{{|C_v|-1\choose2}}",
        interpretation="Higher means the node is a stronger single-node structural cut in this snapshot.",
        limitations="Only a singleton structural cut; it is not a fault tree, cascade or capacity result.",
        cost="medium",
    ),
    _method(
        "structure.path_diversity", "Edge-disjoint path diversity", "Communities and bridges",
        "How much of the node's component is connected by at least two structural edge-disjoint paths?",
        "Share of same-component nodes in the node's bridge-free component.",
        inputs=["simple undirected structural projection"],
        calculation="Removes every structural bridge and measures the retained bridge-connected component share.",
        formula="Bridge-free reach share", raw_latex=r"D_p(v)=(|C_{2e}(v)|-1)/( |C(v)|-1)",
        interpretation="Higher indicates greater recorded edge-route diversity.",
        limitations="Does not measure node-disjoint routes, capacity, delay or substitutability.",
        cost="medium",
    ),
    _method(
        "structure.component_reachability", "Component and reachability", "Classical graph",
        "How much of the selected graph shares this object's structural component?",
        "Graph-wide reachable share and component count on the undirected structural projection.",
        inputs=["simple undirected structural projection"],
        calculation="Enumerates connected components and divides same-component peers by all other nodes.",
        formula="Reachable component share", raw_latex=r"R_c(v)=(|C(v)|-1)/(n-1)",
        interpretation="Higher means a larger share of the recorded graph is structurally connected.",
        limitations="Undirected reach does not establish direction, permission, flow or causal influence.",
    ),
    _method(
        "structure.typed_temporal_motifs", "Directed typed temporal motifs", "Temporal",
        "Which documented temporal interaction patterns recur around this object?",
        "Counts ontology-approved directed motifs whose event ordering falls inside an explicit window.",
        inputs=["event-centric typed graph", "valid event times", "motif catalogue", "window"],
        calculation="Production extension point; never collapses report or ingestion order into event order.",
        formula="Typed motif count", raw_latex=r"M_m(v,\Delta t)=\sum_q\mathbb{1}[q\cong m,\,span(q)\le\Delta t]",
        interpretation="Counts recurring typed temporal patterns, not causal mechanisms.",
        limitations="Unavailable on the current static snapshot; motif search can be expensive and reporting bursts can mislead.",
        enabled=False, cost="high",
    ),
    _method(
        "resilience.substitute_count", "Recorded substitute count", "Resilience",
        "How many same-type objects have an explicit function match or shared typed role?",
        "Count of defensible structural substitute candidates with their identifiers retained in the trace.",
        inputs=["object type", "explicit function metadata or typed neighbour roles"],
        calculation="Requires the same object type and either an explicit function match or a shared direction–predicate–neighbour signature.",
        formula="Candidate count", raw_latex=r"S(v)=|\{u:type(u)=type(v)\land role(u)\cap role(v)\ne\varnothing\}|",
        output="Non-negative count plus fixed-cap display scale",
        interpretation="Higher means more recorded structural alternatives.",
        limitations="A candidate is not proven interchangeable; missing collection can suppress the count.",
    ),
    _method(
        "resilience.substitute_diversity", "Substitute diversity", "Resilience",
        "How different are the recorded structural neighbourhoods of substitute candidates?",
        "Average pairwise typed-neighbourhood Jaccard dissimilarity across substitute candidates.",
        inputs=["recorded substitute candidates", "typed neighbourhoods"],
        calculation="Averages one minus Jaccard similarity over candidate signature pairs.",
        formula="Mean Jaccard dissimilarity", raw_latex=r"D_s=\frac{1}{|P|}\sum_{(i,j)\in P}(1-J(R_i,R_j))",
        interpretation="Higher means recorded alternatives are less structurally identical.",
        limitations="Structural diversity is not geographic, ownership, capacity or correlated-risk independence.",
    ),
    _method(
        "resilience.alternative_coverage", "Alternate supplier, route or dependency coverage", "Resilience",
        "How much structural alternate-path and substitute coverage is recorded?",
        "Display composite of incident bypass coverage and fixed-cap substitute coverage.",
        inputs=["alternate-path tests", "recorded substitute count"],
        calculation="Combines 60% path coverage with 40% substitute coverage and retains both components.",
        formula="Structural coverage proxy", raw_latex=r"A_c=0.6(1-L_{alt})+0.4\min(1,S/4)",
        interpretation="Higher means more recorded structural alternatives.",
        limitations="Structural proxy only; does not account for capacity, timing, cost or real interchangeability.",
    ),
    _method(
        "resilience.dependency_exposure", "Dependency exposure", "Resilience",
        "How many configured dependency relationships are incident on this object?",
        "Count of incident relationships in the documented dependency predicate set.",
        inputs=["typed projection", "configured dependency predicates"],
        calculation="Counts fused incident dependency relationships and applies a fixed display cap.",
        formula="Typed exposure count", raw_latex=r"E_d(v)=\sum_{e\ni v}\mathbb{1}[type(e)\in R_d]",
        interpretation="Higher means more recorded dependency exposure in this projection.",
        limitations="Direction, capacity and actual loss are not represented by the count.",
    ),
    _method(
        "resilience.single_point_failure", "Single-point structural proxy", "Resilience",
        "Is this object an un-substituted structural cut or wholly bridge-exposed endpoint?",
        "A conservative Boolean structural flag combining cut status, bridge exposure and recorded substitute absence.",
        inputs=["articulation status", "bridge-edge exposure", "recorded substitutes"],
        calculation="True only for a connected object with no recorded substitute and either articulation status or complete incident bridge exposure.",
        formula="Structural indicator", raw_latex=r"I_{sp}=\mathbb{1}[S=0\land(A=1\lor E_b=1)]",
        output="Boolean structural proxy",
        interpretation="True means the static graph records a possible single structural dependency.",
        limitations="Must never be described as actual failure probability or causal system failure.",
    ),
    _method(
        "resilience.fragility_band", "Structural fragility band", "Resilience",
        "How strongly do non-redundancy, non-substitutability and single-point structure coincide?",
        "A display-only band over three transparent structural proxies.",
        inputs=["alternate-path loss", "non-substitutability", "single-point structural proxy"],
        calculation="Applies fixed weights of 40%, 30% and 30% and retains each term in the trace.",
        formula="Structural fragility", raw_latex=r"F_s=0.4L_{alt}+0.3N+0.3I_{sp}",
        interpretation="Higher means more structural fragility signals in this projection.",
        limitations="Not a failure probability, causal cascade, reliability estimate or recovery forecast.",
    ),
    _method(
        "resilience.structural_stress_reach", "Structural stress-test reach", "Resilience",
        "Which mission-seed-scope objects lose structural reach after this object is removed?",
        "Named lost-reach set from a static node-deletion stress test.",
        inputs=["versioned mission seeds", "structural projection"],
        calculation="Compares seed-scope reach before and after removing one object.",
        formula="Lost seed-reach set", raw_latex=r"L_s(v)=R(S,G)\setminus R(S\setminus\{v\},G-v)",
        output="Object identifiers plus fractional lost reach",
        interpretation="Identifies structurally affected recorded objects in the explicit seed scope.",
        limitations="Static deletion is not a causal cascade and omits capacity, adaptation and recovery.",
        cost="medium",
    ),
    _method(
        "resilience.recovery_difficulty", "Recovery difficulty", "Resilience",
        "How difficult would restoration or substitution be after degradation?",
        "Context-bound recovery assessment using explicit repair time, resources, access, substitutes and restoration constraints.",
        inputs=["recovery-time distribution", "resources", "access constraints", "substitution plan"],
        calculation="Applies a versioned recovery rubric or validated model only when its inputs exist.",
        formula="Configured recovery model", raw_latex=r"D_r=f(T_r,R,A,S)",
        interpretation="Higher means more difficult or slower expected recovery under the stated assumptions.",
        limitations="Unavailable from topology alone; structural non-redundancy cannot stand in for recovery time.",
        enabled=False,
    ),
    _method(
        "multilayer.per_layer_centrality", "Per-layer typed degree", "Multilayer",
        "How many mapped relationships does the object have in each documented layer?",
        "Incident typed degree reported separately for every configured operational layer.",
        inputs=["relation-to-layer mapping", "typed incident relationships"],
        calculation="Counts fused incident relationships by layer while retaining an unmapped bucket.",
        formula="Layer degree", raw_latex=r"k_l(v)=|\{e\ni v:layer(e)=l\}|",
        output="Layer-to-count mapping plus fixed-cap display scale",
        interpretation="Shows where recorded connectivity occurs without collapsing incompatible layers.",
        limitations="Counts are collection-sensitive and do not imply equal semantics or weights across layers.",
        layers=["all configured layers"],
    ),
    _method(
        "multilayer.cross_layer_participation", "Cross-layer participation", "Multilayer",
        "How evenly are this object's incident relationships distributed across documented layers?",
        "Layer-conditioned participation coefficient that retains unmapped relationships as a visible separate group.",
        inputs=["relation-to-layer mapping", "typed incident relationships"],
        calculation="Computes one minus the sum of squared incident layer-degree shares.",
        formula="Cross-layer participation", raw_latex=r"P_L(v)=1-\sum_l(k_{v,l}/k_v)^2",
        interpretation="Higher means recorded connections are more evenly distributed across mapped layers.",
        limitations="A high value is not operational importance; layer definitions and missing relationships materially affect it.",
        layers=["all configured layers"],
    ),
    _method(
        "multilayer.layer_bridge_exposure", "Layer-specific bridge exposure", "Multilayer",
        "What share of mapped incident relationships are endpoint bridges inside their own layer?",
        "Per-layer Tarjan bridge analysis aggregated only after each coherent layer is analysed separately.",
        inputs=["documented layer mapping", "per-layer structural projections"],
        calculation="Finds bridges separately within each layer and divides incident bridge layer/endpoint pairs by mapped incident layer/endpoint pairs.",
        formula="Layer bridge share", raw_latex=r"B_L(v)=\sum_l|B_l\cap E_v|/|E_{v,mapped}|",
        interpretation="Higher means more within-layer incident structure lacks an endpoint-pair bypass.",
        limitations="Not a physical failure or cross-layer cascade estimate.",
        layers=["all configured layers"], cost="medium",
    ),
    _method(
        "multilayer.layer_to_layer_reach", "Layer-to-layer reach", "Multilayer",
        "Which objects are reached through mapped two-hop transitions between layers?",
        "Distinct two-hop reachable objects grouped by the first traversed operational layer.",
        inputs=["typed projection", "relation-to-layer mapping"],
        calculation="Enumerates mapped two-hop structural walks and deduplicates destination objects.",
        formula="Two-hop layer reach", raw_latex=r"R_{l_1,l_2}(v)=|\{u:v\xrightarrow{l_1}x\xrightarrow{l_2}u\}|",
        output="Layer reach mapping plus graph-relative share",
        interpretation="Shows recorded short cross-layer reach without assuming flow.",
        limitations="Undirected structural walks ignore direction and do not establish operational accessibility.",
        layers=["all configured layers"],
    ),
    _method(
        "multilayer.path_diversity", "Multilayer path diversity", "Multilayer",
        "How many distinct mapped two-hop layer sequences occur around this object?",
        "Count of distinct ordered layer-pair sequences and their deduplicated destinations.",
        inputs=["typed projection", "relation-to-layer mapping"],
        calculation="Enumerates ordered layer pairs over two-hop structural walks and applies a fixed display cap.",
        formula="Layer-sequence diversity", raw_latex=r"D_L(v)=|\{(l_1,l_2):v\xrightarrow{l_1}x\xrightarrow{l_2}u\}|",
        interpretation="Higher means more varied recorded layer sequences.",
        limitations="Sequence count does not measure independent routes, capacity or temporal feasibility.",
        layers=["all configured layers"],
    ),
    _method(
        "multilayer.layer_removal_sensitivity", "Layer-removal sensitivity", "Multilayer",
        "How much structural reach is lost when one mapped layer is removed?",
        "Maximum reach loss across one-layer-at-a-time static deletion tests.",
        inputs=["typed projection", "relation-to-layer mapping"],
        calculation="Removes every relationship in each observed layer in turn and records fractional reach loss.",
        formula="Maximum layer reach loss", raw_latex=r"S_L(v)=\max_l\frac{|R(v,G)\setminus R(v,G-E_l)|}{|R(v,G)|}",
        interpretation="Higher identifies greater structural dependence on one mapped layer.",
        limitations="Static structural proxy only; adaptation, capacity and cross-layer substitution are absent.",
        layers=["all configured layers"], cost="medium",
    ),
])

METHODS.extend([
    _method(
        "evidence.directness", "Evidence directness", "Evidence",
        "How directly does the evidence observe or document the asserted fact?",
        "An explicit information-level assessment of direct observation versus hearsay or inference.",
        inputs=["assertion evidence", "directness assessment", "assessor or rule provenance"],
        calculation="Maps only a recorded directness grade through a versioned scale.",
        formula="Configured directness mapping", raw_latex=r"D_e\in[0,1]",
        interpretation="Higher means the supporting information is more direct.",
        limitations="Must not be inferred from source prestige or document format; unavailable when unrecorded.",
        enabled=False,
    ),
    _method(
        "evidence.extraction_certainty", "Extraction certainty", "Evidence",
        "How certain is the grounded extraction span and predicate mapping?",
        "Recorded extraction certainty tied to exact source spans and extractor version.",
        inputs=["source span", "extractor output", "calibrated extraction assessment"],
        calculation="Returns a calibrated or analyst-reviewed extraction value only with exact span provenance.",
        formula="Calibrated extraction assessment", raw_latex=r"C_x=P(\text{correct extraction}\mid x,m)",
        interpretation="Higher means stronger support that the text was extracted and typed correctly.",
        limitations="Raw model scores are not probabilities; node-level aggregation requires a documented rule.",
        enabled=False,
    ),
    _method(
        "evidence.entity_resolution_certainty", "Entity-resolution certainty", "Evidence",
        "How certain is the link from an extracted mention to this canonical object?",
        "Recorded resolution assessment with candidate set, features and review status.",
        inputs=["mention", "candidate entities", "resolution decision", "calibration or analyst review"],
        calculation="Uses a calibrated resolver value or an explicit analyst decision and preserves alternatives.",
        formula="Resolution assessment", raw_latex=r"C_r=P(e=e^*\mid m,X)",
        interpretation="Higher means the mention-to-entity link is better supported.",
        limitations="Name similarity alone is insufficient; raw similarity is not probability.",
        enabled=False,
    ),
    _method(
        "evidence.supporting_strength", "Supporting-evidence strength", "Evidence",
        "How strong is the lineage-adjusted evidence supporting the assessment?",
        "Non-compensatory aggregation of directness, credibility, reliability, extraction, resolution, validity and independent lineage.",
        inputs=["supporting assertions", "source lineage", "quality dimensions", "decision time"],
        calculation="Aggregates only compatible supporting assertions with explicit lineage discount and documented non-compensatory rules.",
        formula="Configured lineage-aware support", raw_latex=r"S_+=g(\{q_i,l_i\}_{i:y_i=+})",
        interpretation="Higher means stronger relevant support, kept separate from disconfirming evidence.",
        limitations="Unavailable without assertion-level provenance and quality assessments; volume alone is not strength.",
        enabled=False,
    ),
    _method(
        "evidence.disconfirming_strength", "Disconfirming-evidence strength", "Evidence",
        "How strong is the lineage-adjusted evidence against the assessment?",
        "Separate aggregation of compatible disconfirming assertions using the same quality and lineage rules as support.",
        inputs=["disconfirming assertions", "source lineage", "quality dimensions", "decision time"],
        calculation="Aggregates disconfirming evidence without subtracting it invisibly from supporting evidence.",
        formula="Configured lineage-aware challenge", raw_latex=r"S_-=g(\{q_i,l_i\}_{i:y_i=-})",
        interpretation="Higher means stronger relevant challenge or counterevidence.",
        limitations="Absence of disconfirming evidence is not proof of truth; unavailable without compatible assertion sets.",
        enabled=False,
    ),
    _method(
        "evidence.source_lineage_diversity", "Source-lineage diversity", "Evidence",
        "How diverse are the independent originating lineages behind this evidence set?",
        "Effective diversity of origin lineages after derivative reporting is collapsed.",
        inputs=["source-dependency graph", "origin lineage ids"],
        calculation="Counts or computes effective diversity over originating lineages, never outlets or documents alone.",
        formula="Effective lineage diversity", raw_latex=r"D_l=1/\sum_l p_l^2",
        output="Effective lineage count plus bounded display diagnostic",
        interpretation="Higher means evidence comes from more diverse recorded origins.",
        limitations="Unavailable when derivation is unknown; apparent diversity can still share upstream collection.",
        enabled=False,
    ),
    _method(
        "evidence.unresolved_status", "Unresolved-evidence status", "Evidence",
        "Which explicit evidence requirements or conflicts remain unresolved?",
        "A categorical assurance status derived from named requirements, missing fields and adjudication state.",
        inputs=["evidence requirements", "adjudication state", "access scope"],
        calculation="Evaluates a versioned checklist and returns named unresolved items rather than a generic missingness score.",
        formula="Rule-derived status", raw_latex=r"U_e=\{r\in R:status(r)\ne resolved\}",
        output="Categorical status and unresolved requirement identifiers",
        interpretation="Shows what remains unresolved and why.",
        limitations="A complete checklist cannot prove truth; restricted evidence may yield an authorised-view-specific status.",
        enabled=False,
    ),
    _method(
        "evidence.confidence_band", "Evidence-confidence band", "Evidence",
        "What evidential assurance band follows from the complete evidence profile?",
        "A display band over the versioned evidential-confidence profile with vetoes for missing provenance or unresolved material conflict.",
        inputs=["complete evidential-confidence profile", "veto conditions"],
        calculation="Bands only a complete non-renormalised profile; unavailable contributors cannot be silently replaced or reweighted.",
        formula="Versioned profile band", raw_latex=r"B_e=b(S_e,V)",
        output="Configured categorical band",
        interpretation="Summarises evidence assurance, not mission consequence or operational importance.",
        limitations="Unavailable while required contributors are missing; thresholds require validation evidence.",
        enabled=False,
    ),
    _method(
        "collection.estimated_latency", "Estimated collection latency", "Collection",
        "How long could a specific collection option take to return usable information?",
        "Explicit latency estimate or distribution for a named collection option and deadline.",
        inputs=["collection option", "latency estimate or distribution", "decision deadline"],
        calculation="Returns the recorded estimate and deadline compatibility; it is not inferred from source availability.",
        formula="Recorded latency distribution", raw_latex=r"T_c\sim F_c(t)",
        output="Duration or distribution with deadline fit",
        interpretation="Longer latency can reduce usefulness for a time-bounded decision.",
        limitations="Sensitive capability details require access control; unavailable when no option is specified.",
        enabled=False,
    ),
    _method(
        "collection.estimated_cost", "Estimated collection cost", "Collection",
        "What authorised cost estimate is recorded for a specific collection option?",
        "Context-specific financial, time, risk or opportunity cost stored with units and assessor provenance.",
        inputs=["collection option", "cost dimensions", "units", "authorised assessor"],
        calculation="Reports explicit cost dimensions and applies a rubric only where policy permits.",
        formula="Configured multi-dimensional cost", raw_latex=r"C_c=f(c_{money},c_{time},c_{risk},c_{opp})",
        output="Cost vector and optional configured band",
        interpretation="Higher means more costly under the recorded dimensions.",
        limitations="Cannot be inferred from missing information; may be restricted by access controls.",
        enabled=False,
    ),
    _method(
        "collection.value_band", "Collection-value band", "Collection",
        "What collection-priority band follows from the complete collection profile?",
        "A configured band over decision sensitivity, unresolved consequence, assessment-change likelihood, urgency and feasibility.",
        inputs=["complete collection-priority profile", "versioned band thresholds"],
        calculation="Bands only the complete non-renormalised collection profile with named veto conditions.",
        formula="Versioned collection band", raw_latex=r"B_c=b(S_c,V)",
        output="Configured categorical band",
        interpretation="Higher means greater expected decision value and feasibility for the specific question.",
        limitations="Unavailable when required inputs are missing; generic information gaps receive no positive bonus.",
        enabled=False,
    ),
    _method(
        "collection.expected_value_information", "Expected value of information", "Collection",
        "How much expected decision utility could a collection option add?",
        "Production extension point for expected value of sample information over explicit alternatives, utilities, priors and observations.",
        inputs=["decision alternatives", "utility model", "prior", "observation model", "collection option"],
        calculation="Computes expected utility with and without the proposed observation and subtracts explicit cost when configured.",
        formula="Expected value of sample information", raw_latex=r"EVSI=\mathbb{E}_Y[\max_a\mathbb{E}(U(a,\theta)|Y)]-\max_a\mathbb{E}[U(a,\theta)]",
        interpretation="Positive value indicates modeled expected decision benefit before or after recorded cost, as labelled.",
        limitations="Unavailable without a validated decision and observation model; highly sensitive to utilities and priors.",
        enabled=False, cost="high",
    ),
])

METHODS.extend([
    _method(
        "temporal.new_relationships", "New relationships", "Temporal",
        "Which relationships first became valid or observable in the current comparison window?",
        "Set difference over compatible typed relationship identities using valid or observation time, never ingestion time alone.",
        inputs=["two versioned snapshots or event history", "valid/observation time", "comparison windows"],
        calculation="Compares canonical relationship identities across windows and retains time-field provenance.",
        formula="Windowed set difference", raw_latex=r"E_{new}=E_{t_1}\setminus E_{t_0}",
        output="Relationship identifiers and counts",
        interpretation="Identifies newly recorded valid relationships within the defined comparison.",
        limitations="Unavailable on one snapshot; a reporting or bulk-ingestion spike is not automatically operational change.",
        enabled=False,
    ),
    _method(
        "temporal.expired_relationships", "Expired relationships", "Temporal",
        "Which relationships ceased to be valid in the current decision window?",
        "Relationships whose explicit validity interval ended between comparable windows.",
        inputs=["complete valid-time intervals", "decision time", "prior snapshot"],
        calculation="Checks interval endings against the versioned decision window.",
        formula="Validity expiry", raw_latex=r"E_{expired}=\{e:t^{valid}_{end}(e)\in(t_0,t_1]\}",
        output="Relationship identifiers and counts",
        interpretation="Identifies explicitly expired assertions, not merely old reports.",
        limitations="Missing valid-to dates cannot be treated as current or expired; retraction is a separate state.",
        enabled=False,
    ),
    _method(
        "temporal.relationship_state_change", "Relationship polarity or status change", "Temporal",
        "Which compatible relationships changed polarity, review status or epistemic state?",
        "Versioned comparison of the same canonical relationship identity across time.",
        inputs=["assertion history", "canonical relationship identity", "polarity and status versions"],
        calculation="Compares state fields across ordered versions and preserves both records.",
        formula="State transition set", raw_latex=r"\Delta E_s=\{e:s_{t_1}(e)\ne s_{t_0}(e)\}",
        output="Relationship transitions",
        interpretation="Shows recorded state changes requiring review or explanation.",
        limitations="Unavailable without history; edits, corrections and operational change must remain distinguishable.",
        enabled=False,
    ),
    _method(
        "temporal.activity_rate", "Activity rate", "Temporal",
        "What valid-time event rate is observed in the specified window?",
        "Typed event count per explicit exposure window, separated from reporting and ingestion rate.",
        inputs=["event-centric records", "valid event time", "window duration"],
        calculation="Counts compatible events by valid time and divides by exposure duration.",
        formula="Windowed event rate", raw_latex=r"\lambda_r=|E_r[t_0,t_1]|/(t_1-t_0)",
        output="Events per configured time unit",
        interpretation="Higher means more recorded valid-time events per unit exposure.",
        limitations="Unavailable from static relations; collection intensity and missing events can bias rates.",
        enabled=False,
    ),
    _method(
        "temporal.centrality_change", "Centrality change", "Temporal",
        "How did a comparable typed centrality diagnostic change between windows?",
        "Difference and rank interval for the same metric on schema-compatible time projections.",
        inputs=["comparable typed projections", "same centrality configuration", "two or more windows"],
        calculation="Recomputes the same metric per window and reports absolute, relative and rank change.",
        formula="Metric change", raw_latex=r"\Delta C(v)=C_{t_1}(v)-C_{t_0}(v)",
        output="Value and rank change with windows",
        interpretation="Shows structural change under a fixed metric definition.",
        limitations="Graph coverage, ontology and collection changes can masquerade as operational change.",
        enabled=False, cost="medium",
    ),
    _method(
        "temporal.community_role_change", "Community-role change", "Temporal",
        "Did the object's community assignment or role change across comparable windows?",
        "Aligned community and within-community role comparison across stable seeded runs.",
        inputs=["communities per window", "partition alignment", "role definitions", "stability runs"],
        calculation="Aligns partitions and compares role labels only when assignments are sufficiently stable.",
        formula="Aligned role transition", raw_latex=r"\Delta r(v)=\mathbb{1}[align(r_{t_0}(v))\ne r_{t_1}(v)]",
        output="Role transition and stability context",
        interpretation="Flags a structural community-role change for analyst interpretation.",
        limitations="Unavailable without stable partitions; label switching and resolution changes can create false change.",
        enabled=False, cost="high",
    ),
    _method(
        "temporal.contradiction_change", "Contradiction change", "Temporal",
        "How did the compatible unresolved contradiction set change?",
        "Difference in material contradiction objects after scope, time and lineage compatibility checks.",
        inputs=["versioned contradiction objects", "compatible assertion scopes", "decision windows"],
        calculation="Tracks opened, resolved and severity-changed contradiction identities.",
        formula="Contradiction-set change", raw_latex=r"\Delta K=K_{t_1}\triangle K_{t_0}",
        output="Opened, resolved and changed contradiction ids",
        interpretation="Shows movement in material unresolved conflicts.",
        limitations="Absence of detected conflict is not agreement; changing evidence access can alter the visible set.",
        enabled=False,
    ),
    _method(
        "temporal.evidence_confidence_change", "Evidence-confidence change", "Temporal",
        "How did evidential assurance change between comparable decision times?",
        "Change in a complete versioned evidence profile with contributor-level attribution.",
        inputs=["complete evidence profiles", "same profile version", "decision times"],
        calculation="Compares profile values and named contributors without renormalising missing dimensions.",
        formula="Evidence profile change", raw_latex=r"\Delta S_e=S_e(t_1)-S_e(t_0)",
        output="Profile and contributor changes",
        interpretation="Shows whether recorded evidence assurance strengthened or weakened.",
        limitations="Unavailable when either profile is incomplete or differently configured.",
        enabled=False,
    ),
    _method(
        "temporal.recurrence", "Temporal recurrence", "Temporal",
        "Does a comparable typed event pattern recur over valid time?",
        "Intervals and recurrence count for ontology-compatible event types and participants.",
        inputs=["event-centric graph", "valid event times", "recurrence identity rule"],
        calculation="Groups comparable events, orders them by valid time and reports inter-event intervals.",
        formula="Recurrence intervals", raw_latex=r"\Delta t_i=t_i-t_{i-1}",
        output="Count and interval distribution",
        interpretation="Identifies repeated recorded event patterns.",
        limitations="Static assertions and repeated reports of one event must not be counted as recurrence.",
        enabled=False,
    ),
    _method(
        "temporal.burst", "Collection-normalised burst detection", "Temporal",
        "Is valid-time activity unusually concentrated after adjusting for collection volume?",
        "Burst detector over event-time counts with collection exposure and source-lineage controls.",
        inputs=["event-time series", "collection exposure", "source lineages", "baseline"],
        calculation="Applies a configured burst detector only after exposure normalisation and minimum-history checks.",
        formula="Detector-specific burst statistic", raw_latex=r"Z_t=(x_t-\mathbb{E}[x_t|C_t])/\sqrt{Var(x_t|C_t)}",
        interpretation="Higher indicates unusual activity relative to the documented collection-adjusted baseline.",
        limitations="Unavailable without history; bulk imports and reporting campaigns can create false bursts.",
        enabled=False,
    ),
    _method(
        "temporal.stability", "Temporal stability", "Temporal",
        "How consistently does a relationship or metric persist across comparable windows?",
        "Retention and value-variation diagnostic over repeated valid-time observations.",
        inputs=["comparable windows", "stable identity", "minimum observation count"],
        calculation="Reports persistence share and configured variation statistic across windows.",
        formula="Window persistence", raw_latex=r"S_t=|\{w:e\in E_w\}|/|W|",
        interpretation="Higher indicates more persistent recorded state across observed windows.",
        limitations="Missing collection periods are not evidence of absence; window selection matters.",
        enabled=False,
    ),
    _method(
        "temporal.time_decayed_relevance", "Time-decayed relevance", "Temporal",
        "How relevant is an observation at the decision time under an explicit decay policy?",
        "Recency transform anchored to event or observation time and an ontology-specific half-life.",
        inputs=["valid observation time", "decision time", "configured half-life"],
        calculation="Applies decay only to eligible evidence types and retains the un-decayed value.",
        formula="Exponential half-life decay", raw_latex=r"R_t=2^{-\Delta t/h}",
        interpretation="Higher means more temporally recent under the stated half-life.",
        limitations="Unavailable without defensible time and half-life; recent evidence is not necessarily more reliable.",
        enabled=False,
    ),
    _method(
        "temporal.emerging_node", "Emerging-node indicator", "Temporal",
        "Is this object's valid-time activity or role increasing beyond its collection-adjusted baseline?",
        "Composite indicator over new relationships, activity change and stable rank change with minimum-history gates.",
        inputs=["temporal relationship history", "collection exposure", "stable metric runs"],
        calculation="Applies a configured rule only when all baseline and exposure checks pass.",
        formula="Configured emerging-node rule", raw_latex=r"I_{emerge}(v)=g(\Delta E_v,\Delta_a,\Delta rank_v)",
        output="Boolean or configured band with trace",
        interpretation="Flags a node for review as structurally or operationally emerging.",
        limitations="Unavailable on a static snapshot; reporting spikes must not automatically trigger it.",
        enabled=False,
    ),
    _method(
        "temporal.emerging_relationship", "Emerging-relationship indicator", "Temporal",
        "Is a typed relationship newly recurring or strengthening beyond a collection-adjusted baseline?",
        "Relationship-level indicator over first-seen time, recurrence, support and compatible status change.",
        inputs=["relationship history", "event/valid time", "collection exposure", "lineage-aware evidence"],
        calculation="Applies a configured relationship-specific rule with minimum-history and evidence gates.",
        formula="Configured emerging-edge rule", raw_latex=r"I_{emerge}(e)=g(t_{first},recurrence,\Delta support)",
        output="Boolean or configured band with trace",
        interpretation="Flags a relationship for analyst review, not acceptance.",
        limitations="Unavailable without history; a newly ingested old report is not a new operational relationship.",
        objects=["relationship"], enabled=False,
    ),
])

METHODS.extend([
    _method(
        "resilience.capacity_flow", "Capacity-aware flow analysis", "Resilience modelling",
        "How do explicit capacities, demands and routing constraints affect feasible flow under stress?",
        "Adapter contract for a typed capacity-constrained flow model with scenario and solver provenance.",
        inputs=["directed network", "capacity", "demand", "flow conservation", "scenario constraints"],
        calculation="Runs a pinned solver only when units, capacities and demands are complete and compatible.",
        formula="Maximum feasible flow", raw_latex=r"\max\sum_{(s,j)}f_{sj}\quad s.t.\ 0\le f_{ij}\le c_{ij}",
        output="Flow, unmet demand, binding constraints and scenario trace",
        interpretation="Quantifies modeled feasible flow under explicit scenario assumptions.",
        limitations="Unavailable on topology alone; results depend on units, demand, routing and solver assumptions.",
        objects=["scenario", "node", "relationship"], enabled=False, cost="high",
    ),
    _method(
        "resilience.fault_tree", "Fault-tree analysis", "Resilience modelling",
        "Which combinations of explicit component failure events produce the defined top event?",
        "Adapter for audited Boolean fault trees, minimal cut sets and optional probability calculation.",
        inputs=["top event", "AND/OR gates", "base failure events", "probabilities if quantitative"],
        calculation="Enumerates minimal cut sets and calculates probability only when independence or dependence assumptions are explicit.",
        formula="OR gate under independence", raw_latex=r"P(T)=1-\prod_i(1-P(E_i))",
        output="Tree, minimal cut sets and optional probability with assumptions",
        interpretation="Identifies modeled logical failure combinations.",
        limitations="Unavailable without an engineered fault tree; topology cannot supply failure logic or probabilities.",
        objects=["scenario", "system"], enabled=False, cost="high",
    ),
    _method(
        "resilience.bayesian_network", "Bayesian network analysis", "Resilience modelling",
        "How do explicit conditional dependencies update system-state beliefs under evidence?",
        "Adapter for a validated directed acyclic graphical model with pinned conditional probability tables.",
        inputs=["Bayesian network DAG", "state definitions", "conditional probability tables", "observations"],
        calculation="Performs exact or declared approximate inference and reports convergence or approximation diagnostics.",
        formula="Bayesian factorisation", raw_latex=r"P(X_1,\ldots,X_n)=\prod_iP(X_i|Pa(X_i))",
        output="Posterior distributions and inference trace",
        interpretation="Updates modeled beliefs conditional on the supplied observations and network.",
        limitations="Unavailable without validated CPTs; graph relationships are not automatically causal Bayesian edges.",
        objects=["scenario", "system"], enabled=False, cost="high",
    ),
    _method(
        "resilience.reliability_model", "Reliability or system-dynamics model", "Resilience modelling",
        "How does system performance evolve under explicit failure, repair, delay and feedback assumptions?",
        "Adapter contract for reliability block diagrams, Markov models or system-dynamics simulation.",
        inputs=["system structure", "failure/repair distributions", "capacity", "delays", "feedback equations"],
        calculation="Runs only a named, versioned model with unit checks, scenario inputs and sensitivity outputs.",
        formula="Model-specific reliability", raw_latex=r"R_{series}(t)=\prod_iR_i(t)",
        output="Reliability or trajectory outputs with scenario and sensitivity trace",
        interpretation="Describes modeled system behaviour under explicit engineering assumptions.",
        limitations="Unavailable without engineering data and validation; structural deletion is not reliability analysis.",
        objects=["scenario", "system"], enabled=False, cost="high",
    ),
    _method(
        "hypothesis.candidate_rank", "Candidate rank", "Hypothesis assurance",
        "Where does this candidate rank within a frozen relation-specific comparison set?",
        "Ordinal rank with candidate universe, tie policy, model version and run id.",
        inputs=["model candidate set", "relation", "raw scores", "frozen run"],
        calculation="Sorts only comparable relation-specific candidates and preserves ties and comparison-set size.",
        formula="Ordinal relation-specific rank", raw_latex=r"rank_r(h)=1+|\{h':s_r(h')>s_r(h)\}|",
        output="Rank and comparison-set size",
        interpretation="Lower rank means the model ordered the candidate earlier in that frozen set.",
        limitations="Rank is not probability or evidence and is incomparable across different candidate universes.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.model_abstention", "Model abstention", "Hypothesis assurance",
        "Did the candidate model decline to make a supported prediction?",
        "Explicit abstention state derived from calibrated coverage, out-of-domain or constraint rules.",
        inputs=["candidate model output", "abstention policy", "domain checks"],
        calculation="Evaluates the pinned abstention policy and records every triggering rule.",
        formula="Abstention rule", raw_latex=r"A(h)=\mathbb{1}[h\notin\Gamma_\alpha(x)\lor OOD(x)]",
        output="Boolean and reason codes",
        interpretation="True means the model does not provide a supported candidate assertion.",
        limitations="Requires calibrated or validated abstention policy; missing output is not automatically abstention.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.prediction_set_size", "Prediction-set size", "Hypothesis assurance",
        "How many relation labels or candidate outcomes remain in the calibrated prediction set?",
        "Predicate-conditional conformal set size and achieved validation coverage.",
        inputs=["calibration set", "nonconformity scores", "target coverage", "candidate outputs"],
        calculation="Builds a predicate-conditional conformal set only with sufficient exchangeable calibration data.",
        formula="Conformal set", raw_latex=r"\Gamma_\alpha(x)=\{y:s(x,y)\le q_{1-\alpha}\}",
        output="Set members, size, target and observed coverage",
        interpretation="Larger sets indicate less specific calibrated model output.",
        limitations="Unavailable without adequate relation-specific calibration; exchangeability failures invalidate coverage.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.structural_path_support", "Supporting structural paths", "Hypothesis",
        "Which bounded accepted-graph paths structurally connect the candidate endpoints?",
        "Typed path retrieval from the accepted graph excluding every model-only prediction.",
        inputs=["candidate triple", "accepted typed graph", "path constraints"],
        calculation="Enumerates bounded simple paths with relation sequence, direction and assertion identifiers.",
        formula="Bounded accepted paths", raw_latex=r"P_h=\{p:s\leadsto t,|p|\le k\}",
        output="Typed paths and evidence identifiers",
        interpretation="Provides structural context that may explain a model ranking.",
        limitations="A path is not evidence that the candidate relation is true; common graph leakage patterns require review.",
        objects=["relationship hypothesis"], enabled=False, cost="medium",
    ),
    _method(
        "hypothesis.counterfactual_sensitivity", "Counterfactual path or edge sensitivity", "Hypothesis assurance",
        "Which accepted edges most affect the candidate model score or rank?",
        "Model-specific leave-one-edge or bounded path-removal sensitivity with run provenance.",
        inputs=["candidate model", "frozen accepted graph", "candidate", "perturbation budget"],
        calculation="Re-runs or approximates the pinned model after permitted edge removals and reports score/rank deltas.",
        formula="Candidate score sensitivity", raw_latex=r"\Delta_e s(h)=s_G(h)-s_{G-e}(h)",
        output="Influential edge ids and score/rank deltas",
        interpretation="Shows which graph inputs the model output is sensitive to.",
        limitations="Model explanation only; an influential edge is not causal evidence for the candidate.",
        objects=["relationship hypothesis"], enabled=False, cost="high",
    ),
    _method(
        "hypothesis.symbolic_rule_support", "Symbolic-rule support", "Hypothesis assurance",
        "Which independently mined symbolic rules support or challenge this candidate?",
        "Candidate-level rule matches with rule text, support, body coverage, confidence, paths and exceptions.",
        inputs=["audited AnyBURL/AMIE output", "candidate triple", "rule lineage"],
        calculation="Matches the candidate against accepted, versioned rules and retains supporting and challenging rules separately.",
        formula="Rule match support", raw_latex=r"S_{rule}(h)=\{q:q\models h\}",
        output="Matched rule records",
        interpretation="Shows interpretable historical graph regularities relevant to the candidate.",
        limitations="Rule confidence is not truth probability; leakage, tautology and shared graph inputs can bias support.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.text_evidence_support", "Text-evidence support", "Hypothesis assurance",
        "Which exact source passages support or disconfirm the candidate relationship?",
        "Evidence retrieval and compatibility assessment over exact passages with source lineage.",
        inputs=["candidate triple", "evidence store", "passages", "lineage", "access scope"],
        calculation="Retrieves bounded candidate-relevant passages and separates supporting, disconfirming and unresolved matches.",
        formula="No model score is treated as evidence", raw_latex="",
        output="Passage ids, polarity, lineage and grounded match trace",
        interpretation="Provides direct evidence context for analyst review.",
        limitations="Retrieval can miss evidence and synthesis can misclassify it; analysts must inspect passages.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.time_sensitivity", "Hypothesis time sensitivity", "Hypothesis",
        "How quickly could the candidate become stale or decision-irrelevant?",
        "Candidate-specific validity or forecast-horizon urgency based on explicit event and decision times.",
        inputs=["candidate horizon", "valid/event time", "decision deadline"],
        calculation="Compares explicit candidate and decision horizons using the configured urgency policy.",
        formula="Candidate horizon urgency", raw_latex=r"U_h=\max(0,1-\Delta t_h/T)",
        interpretation="Higher means the candidate requires more time-sensitive review.",
        limitations="Unavailable for static timeless candidates; ingestion time is not event time.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.review_feasibility", "Hypothesis review feasibility", "Hypothesis",
        "Can this candidate be reviewed or collected against within the decision window?",
        "Candidate-specific access, evidence, latency, cost and policy rubric.",
        inputs=["candidate", "review action", "deadline", "constraints"],
        calculation="Applies an attributable versioned rubric to a named review action.",
        formula="Configured review feasibility", raw_latex=r"F_h=f(access,evidence,time,cost,policy)",
        interpretation="Higher means review is more feasible under recorded constraints.",
        limitations="Must not be inferred from model score and may require access-controlled inputs.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.review_priority", "Hypothesis-review priority", "Hypothesis",
        "What review order follows from the complete hypothesis profile?",
        "Non-renormalised profile output over conditional consequence, calibrated plausibility, independent agreement, information gain, urgency and feasibility.",
        inputs=["complete hypothesis-review profile", "versioned thresholds"],
        calculation="Applies the configured profile only when all required contributors are available.",
        formula="Versioned hypothesis profile", raw_latex=r"S_h=\sum_jw_jx_j",
        output="0–1 profile value or unavailable, plus configured band",
        interpretation="Higher means earlier analyst review, never acceptance or operational truth.",
        limitations="Unavailable for incomplete profiles; missing values are not zero or silently reweighted.",
        objects=["relationship hypothesis"], enabled=False,
    ),
    _method(
        "hypothesis.novelty", "Candidate novelty badge", "Hypothesis",
        "How unusual is this candidate inside its frozen comparison set?",
        "Display-only structural novelty diagnostic with comparison-set and model provenance.",
        inputs=["candidate", "frozen comparison set", "novelty definition"],
        calculation="Applies a configured novelty statistic and reports its reference distribution.",
        formula="Method-specific novelty", raw_latex=r"N(h)=g(h;H_{ref})",
        output="Diagnostic badge and reference context",
        interpretation="Higher means more unusual under the stated reference set.",
        limitations="Novelty is not evidence, plausibility, consequence or operational importance and has zero score weight.",
        objects=["relationship hypothesis"], enabled=False,
    ),
])


_BY_ID = {item["id"]: item for item in METHODS}


def method_catalogue() -> list[dict[str, Any]]:
    return deepcopy(METHODS)


def method_definition(identifier: str) -> dict[str, Any]:
    try:
        return deepcopy(_BY_ID[identifier])
    except KeyError as exc:
        raise KeyError(f"Unknown PRIMROSE method {identifier!r}") from exc
